version: "3.9"

services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
  web:
    build: "./"
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - ENVIROMENT=production
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy