version: "3.9"

services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  web:
    build: "./"
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db