name: bank-simulator-ci

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: check lint
        run: |
          npm ci
          npm run lint
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bank_simulator
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: check test
        run: |
          npm ci
          npm run test --detectOpenHandles --maxWorkers=1
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_PORT: 5432
          POSTGRES_DB: bank_simulator
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          ENVIROMENT: production
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      - name: check test
        run: |
          npm ci
          npm run build
